name: Onboarding to Catena-X Automotive Network e.V. (GitHub or Teams)
description: "This issue is only relevant for people whose company is already a member of Catena-X Automotive Network e.V."
title: "[Onboarding] "
labels: ["onboarding", "Catena-X"]
assignees: ["onboarding-team"]
body:
  - type: markdown
    attributes:
      value: "## Onboarding to Catena-X Automotive Network e.V."
  - type: markdown
    attributes:
      value: "Please ensure that your company is already a member of Catena-X Automotive Network e.V. before proceeding. If not, the issue will not be processed further. **Please note: Due to the fact that the repository and the issues are public, anyone can see the information entered.**"
  - type: input
    attributes:
      label: "Your Full Name"
      description: "Please provide your name. This is important to identify/map you with your company."
      placeholder: "Enter your full name"
    validations:
      required: true
  - type: input
    attributes:
      label: "E-Mail"
      description: "This is only important if you also want to get access to the provided Catena-X Microsoft teams tenant."
      placeholder: "email@example.com"
  - type: input
    attributes:
      label: "Microsoft Teams Channel"
      description: "If you added you E-Mail in the prevoius step and you want to get acceess to a dedicated teams (e.g. expert group or committee) please add the name of the group."
      placeholder: "Network Service Committee - Dataspace Connectivity"
  - type: input
    attributes:
      label: "GitHub Handle"
      description: "This is only important if you also want to get access to a dedicated team in Catena-X GitHub. e.g. expert group or committee"
      placeholder: "https://github.com/stephanbcbauer"
  - type: input
    attributes:
      label: "GitHub Teams / Repository"
      description: "If you added you GitHub Handle in the prevoius step and you want to get acceess to a dedicated teams (e.g. expert group or committee) please add the name of the group."
      placeholder: "Dataspace Connectivity"
  - type: input
    attributes:
      label: "Company Name"
      description: "Please provide the official name of your company. This is important, cause you get only acceess, if your company is already a member of Catena-X."
      placeholder: "Enter your company name"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Additional Notes or Questions"
      description: "Any additional information or questions regarding the onboarding process."
    validations:
      required: false